// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SOSurbano_webApi.Data.Context;

#nullable disable

namespace SOSurbano_webApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241205193159_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SOSurbano_webApi.Model.ChamadoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataChamado")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("SOU_STATUS_CHAMADO")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SOU_USER")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("SOU_STATUS_CHAMADO");

                    b.HasIndex("SOU_USER");

                    b.ToTable("SOU_CHAMADO");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.GeneroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("SOU_GENERO");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.HistoricoOcorrenciaModel", b =>
                {
                    b.Property<int>("IdOcorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOcorrencia"));

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("SOU_TIPO_OCORRENCIA")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdOcorrencia");

                    b.HasIndex("SOU_TIPO_OCORRENCIA");

                    b.ToTable("SOU_HISTORICO_OCORRENCIA");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.HistoricoServicoStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("SOU_CHAMADO")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SOU_SERVICO_STATUS")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SOU_VEICULO")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("SOU_CHAMADO");

                    b.HasIndex("SOU_SERVICO_STATUS");

                    b.HasIndex("SOU_VEICULO");

                    b.ToTable("SOU_HISTORICO_STATUS_SERVICO");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("SOU_ROLE");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.StatusChamadoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nome")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("SOU_STATUS_CHAMADO");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.StatusServicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Descricao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("SOU_SERVICO_STATUS");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.TipoDeOcorrenciaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("SOU_TIPO_OCORRENCIA");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RoleId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RoleId");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("SOU_USUARIO");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.VeiculoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Placa")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("SOU_SERVICO_STATUS")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("SOU_SERVICO_STATUS");

                    b.ToTable("SOU_VEICULO");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.ChamadoModel", b =>
                {
                    b.HasOne("SOSurbano_webApi.Model.StatusChamadoModel", "StatusChamadoId")
                        .WithMany()
                        .HasForeignKey("SOU_STATUS_CHAMADO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOSurbano_webApi.Model.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("SOU_USER")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusChamadoId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.HistoricoOcorrenciaModel", b =>
                {
                    b.HasOne("SOSurbano_webApi.Model.TipoDeOcorrenciaModel", "TipoOcorrenciaId")
                        .WithMany()
                        .HasForeignKey("SOU_TIPO_OCORRENCIA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoOcorrenciaId");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.HistoricoServicoStatus", b =>
                {
                    b.HasOne("SOSurbano_webApi.Model.ChamadoModel", "ChamadoId")
                        .WithMany()
                        .HasForeignKey("SOU_CHAMADO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOSurbano_webApi.Model.StatusServicoModel", "StatusServicoId")
                        .WithMany()
                        .HasForeignKey("SOU_SERVICO_STATUS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOSurbano_webApi.Model.VeiculoModel", "VeiculoId")
                        .WithMany()
                        .HasForeignKey("SOU_VEICULO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChamadoId");

                    b.Navigation("StatusServicoId");

                    b.Navigation("VeiculoId");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.UsuarioModel", b =>
                {
                    b.HasOne("SOSurbano_webApi.Model.RoleModel", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SOSurbano_webApi.Model.VeiculoModel", b =>
                {
                    b.HasOne("SOSurbano_webApi.Model.StatusServicoModel", "StatusServicoId")
                        .WithMany()
                        .HasForeignKey("SOU_SERVICO_STATUS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusServicoId");
                });
#pragma warning restore 612, 618
        }
    }
}
