# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sosurbanostaging

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1492aff0f7a34bfcbffc2616c32cc19e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8007ade021414e2498693b3725c5bc97 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1492aff0f7a34bfcbffc2616c32cc19e }}/claytonoliveiratd/sosurbano-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sosurbanostaging'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6d840fa700c0486c8314a3d774146a72 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1492aff0f7a34bfcbffc2616c32cc19e }}/claytonoliveiratd/sosurbano-api:${{ github.sha }}'