# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sosurbanostaging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d3daa2914ecb4d359899e30a23bbb20b }}/claytonoliveiratd/sosurbano-api:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'sosurbanostaging'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_ace3cb8b9419466295b182d55fdcc179 }}
            images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d3daa2914ecb4d359899e30a23bbb20b }}/claytonoliveiratd/sosurbano-api:${{ github.sha }}'
